import { CONFIG } from '../constants/config.js';
import { randomInt, randomChoice, randomName } from '../utils/rng.js';
import { getCellsOfType } from './cityGenerator.js';

const { STAGE, CELL } = CONFIG;

let _idCounter = 0;
export function resetIdCounter() { _idCounter = 0; }
function nextId() { return ++_idCounter; }

export function getStageFromAge(age) {
  if (age < CONFIG.AGE_CHILD_MAX) return STAGE.CHILD;
  if (age < CONFIG.AGE_YOUTH_MAX) return STAGE.YOUTH;
  if (age < CONFIG.AGE_ADULT_MAX) return STAGE.ADULT;
  return STAGE.ELDER;
}

export function createCitizen(rng, city, overrides = {}) {
  const id = nextId();
  const name = randomName(rng);
  const age = overrides.age ?? randomInt(rng, 0, CONFIG.AGE_ADULT_MAX - 1);
  const stage = getStageFromAge(age);

  const streets = [];
  for (let y = 0; y < city.size; y++)
    for (let x = 0; x < city.size; x++)
      if (city.grid[y][x].type === CELL.STREET || city.grid[y][x].type === CELL.RESIDENTIAL)
        streets.push(`${x},${y}`);

  const startCell = randomChoice(rng, streets) || '1,1';
  const [sx, sy] = startCell.split(',').map(Number);
  const colorIndex = randomInt(rng, 0, 5);

  return {
    id,
    name,
    age,
    stage,
    energy: randomInt(rng, 55, 100),
    hunger: randomInt(rng, 5, 45),
    happiness: randomInt(rng, 45, 100),
    cellKey: startCell,
    pixelX: sx * CONFIG.CELL_SIZE + CONFIG.CELL_SIZE / 2,
    pixelY: sy * CONFIG.CELL_SIZE + CONFIG.CELL_SIZE / 2,
    targetCellKey: null,
    path: [],
    pathIndex: 0,
    // Routine: array of behaviors generated by Groq once per day
    routine: [],
    routineIndex: 0,
    routineGeneratedAt: -999, // tick when routine was last generated
    behavior: { action: 'caminar', duration: 10, description: 'Llegando a la ciudad...' },
    behaviorTicksLeft: 10,
    lastBehavior: null,
    personality: null,
    colorIndex,
    relationships: {},
    alive: true,
    isRequestingRoutine: false,
    ...overrides,
  };
}

export function createInitialPopulation(rng, city) {
  const count = randomInt(rng, CONFIG.POP_INITIAL_MIN, CONFIG.POP_INITIAL_MAX);
  const citizens = [];
  for (let i = 0; i < count; i++) {
    citizens.push(createCitizen(rng, city));
  }
  return citizens;
}

export function updateCitizenAge(citizen) {
  citizen.age += 1;
  citizen.stage = getStageFromAge(citizen.age);
}

export function shouldDie(citizen) {
  return citizen.energy <= 0 || citizen.age >= CONFIG.AGE_ELDER_MAX;
}

export function canReproduce(c1, c2) {
  return (
    c1.stage === STAGE.ADULT && c2.stage === STAGE.ADULT &&
    c1.energy > 70 && c2.energy > 70 &&
    c1.happiness > 60 && c2.happiness > 60 &&
    c1.cellKey === c2.cellKey && c1.id !== c2.id
  );
}

export function reproduce(rng, city, p1, p2) {
  const child = createCitizen(rng, city, {
    age: 0, stage: STAGE.CHILD,
    energy: 80, hunger: 20, happiness: 80,
    cellKey: p1.cellKey, pixelX: p1.pixelX, pixelY: p1.pixelY,
  });
  child.colorIndex = rng() > 0.5 ? p1.colorIndex : p2.colorIndex;
  return child;
}

export function applyBehaviorEffect(citizen, action) {
  switch (action) {
    case 'comer':    case 'comprar':
      citizen.energy  = Math.min(100, citizen.energy + 20);
      citizen.hunger  = Math.max(0,   citizen.hunger - 35);
      citizen.happiness = Math.min(100, citizen.happiness + 5);
      break;
    case 'dormir':   case 'descansar':
      citizen.energy  = Math.min(100, citizen.energy + 35);
      citizen.happiness = Math.min(100, citizen.happiness + 5);
      break;
    case 'socializar': case 'jugar':
      citizen.happiness = Math.min(100, citizen.happiness + 18);
      citizen.hunger  = Math.min(100, citizen.hunger + 3);
      break;
    case 'trabajar':
      citizen.energy  = Math.max(0,   citizen.energy - 8);
      citizen.happiness = Math.min(100, citizen.happiness + 8);
      citizen.hunger  = Math.min(100, citizen.hunger + 5);
      break;
    case 'leer':    case 'explorar':
      citizen.happiness = Math.min(100, citizen.happiness + 10);
      citizen.hunger  = Math.min(100, citizen.hunger + 2);
      break;
    case 'caminar':
      citizen.hunger  = Math.min(100, citizen.hunger + 3);
      citizen.energy  = Math.max(0,   citizen.energy - 2);
      break;
    default: break;
  }
}

export function decayAttributes(citizen) {
  // Slow decay — 1 tick = ~1 second, so decay is gentle
  citizen.hunger  = Math.min(100, citizen.hunger + 0.3);
  citizen.energy  = Math.max(0,   citizen.energy - 0.1);
  if (citizen.hunger > 75) {
    citizen.happiness = Math.max(0, citizen.happiness - 0.3);
    citizen.energy    = Math.max(0, citizen.energy - 0.2);
  }
}
