/**
 * Custom Cell Registry
 * 
 * Stores dynamically generated cell types (created via god orders like "crea una estatua").
 * Each custom cell has:
 *   - id: unique string key (e.g. 'estatua')
 *   - label: display name
 *   - emoji: icon for floating text
 *   - drawFn: serialized JS function body that draws the cell on canvas
 *   - behaviorAction: what citizens do near this cell
 *   - worldEffect: { happiness, culture, etc. } delta applied when built
 * 
 * Persists to localStorage so custom cells survive page reloads.
 * The compiled draw functions are cached in memory.
 */

const STORAGE_KEY = 'lamdacity_custom_cells';

// In-memory registry: id → { meta, compiledFn }
const _registry = new Map();

// ── Load from localStorage on startup ────────────────────────────────────────
export function loadCustomCells() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    const cells = JSON.parse(raw);
    for (const cell of cells) {
      _compileAndRegister(cell);
    }
  } catch (e) {
    console.warn('[CustomCells] Failed to load from localStorage:', e);
  }
}

// ── Register a new custom cell ────────────────────────────────────────────────
export function registerCustomCell(cell) {
  _compileAndRegister(cell);
  _persist();
}

function _compileAndRegister(cell) {
  try {
    // drawFn is a function body string: (ctx, px, py, CS, tick, isNight) => { ... }
    // We wrap it in a Function constructor for safe eval
    // eslint-disable-next-line no-new-func
    const fn = new Function('ctx', 'px', 'py', 'CS', 'tick', 'isNight', cell.drawFn);
    _registry.set(cell.id, { ...cell, compiledFn: fn });
  } catch (e) {
    console.warn(`[CustomCells] Failed to compile draw function for "${cell.id}":`, e);
  }
}

function _persist() {
  try {
    const cells = [..._registry.values()].map(({ compiledFn, ...rest }) => rest);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(cells));
  } catch (e) {
    console.warn('[CustomCells] Failed to persist:', e);
  }
}

// ── Query ─────────────────────────────────────────────────────────────────────
export function getCustomCell(id) {
  return _registry.get(id) || null;
}

export function getAllCustomCells() {
  return [..._registry.values()];
}

export function hasCustomCell(id) {
  return _registry.has(id);
}

export function drawCustomCell(id, ctx, px, py, CS, tick, isNight) {
  const cell = _registry.get(id);
  if (!cell?.compiledFn) {
    // Fallback: draw a question mark tile
    ctx.fillStyle = '#2a1a3a';
    ctx.fillRect(px, py, CS, CS);
    ctx.fillStyle = '#c060ff';
    ctx.font = `${CS * 0.6}px serif`;
    ctx.fillText('?', px + CS * 0.25, py + CS * 0.75);
    return;
  }
  try {
    cell.compiledFn(ctx, px, py, CS, tick, isNight);
  } catch (e) {
    // Draw error tile
    ctx.fillStyle = '#3a0a0a';
    ctx.fillRect(px, py, CS, CS);
  }
}

// ── Clear all custom cells ────────────────────────────────────────────────────
export function clearCustomCells() {
  _registry.clear();
  localStorage.removeItem(STORAGE_KEY);
}

// ── Get event triggers for all registered custom cells ────────────────────────
export function getCustomCellEventTriggers() {
  const triggers = [];
  for (const cell of _registry.values()) {
    if (cell.eventTriggers?.length) {
      triggers.push({ cellId: cell.id, label: cell.label, emoji: cell.emoji, triggers: cell.eventTriggers });
    }
  }
  return triggers;
}

// ── Export cell definitions as JS code (for git commit) ───────────────────────
export function exportAsCode() {
  const cells = [..._registry.values()].map(({ compiledFn, ...rest }) => rest);
  return `// Auto-generated custom cells — do not edit manually
// Generated by LAMDACITY god mode
export const CUSTOM_CELLS = ${JSON.stringify(cells, null, 2)};
`;
}
