// Auto-generated custom cells — do not edit manually
// Generated by LAMDACITY god mode
export const CUSTOM_CELLS = [
  {
    "id": "100_aldeanos",
    "label": "100 aldeanos",
    "emoji": "🏛",
    "drawFn": "ctx.fillStyle='#1a1a2a';ctx.fillRect(px,py,CS,CS);ctx.fillStyle='#808080';ctx.beginPath();ctx.arc(px+CS/2,py+CS/2,CS/2-2,0,2*Math.PI);ctx.fill();if(isNight){ctx.fillStyle='rgba(245,200,66,0.3)';ctx.fillRect(px,py,CS,CS);}",
    "behaviorAction": "explorar",
    "worldEffect": {
      "happiness": 5,
      "culture": 5
    },
    "eventTriggers": [
      {
        "condition": "tick % 300 === 0",
        "effect": "magia",
        "news": "Algo ocurre en 100 aldeanos",
        "worldEffect": {
          "happiness": 5
        }
      },
      {
        "condition": "tick % 150 === 0",
        "effect": "generico",
        "news": "La gente se mueve en 100 aldeanos",
        "worldEffect": {
          "culture": 1
        }
      }
    ],
    "confirmacion": "Nueva estructura creada",
    "noticia": "Nueva estructura en la ciudad"
  },
  {
    "id": "volcan",
    "label": "volcán",
    "emoji": "🌋",
    "drawFn": "ctx.fillStyle='#121212';ctx.fillRect(px,py,CS,CS);ctx.fillStyle='#2f2f2f';ctx.beginPath();ctx.arc(px+CS/2,py+CS/2,CS/2,0,2*Math.PI);ctx.fill();if(isNight){ctx.fillStyle='rgba(245,200,66,0.3)';ctx.fillRect(px,py,CS,CS);}",
    "behaviorAction": "explorar",
    "worldEffect": {
      "happiness": 5,
      "culture": 5
    },
    "eventTriggers": [
      {
        "condition": "tick % 300 === 0",
        "effect": "magia",
        "news": "Algo ocurre en volcán",
        "worldEffect": {
          "happiness": 5
        }
      }
    ],
    "confirmacion": "Nueva estructura creada",
    "noticia": "Nueva estructura en la ciudad"
  }
];
